
// @ts-ignore
import url_nightly from './wp-nightly.zip?url';

/**
 * This file was auto generated by packages/playground/wordpress-builds/build/build.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export function getWordPressModuleDetails(wpVersion: string = undefined): { size: number, url: string } {
	switch (wpVersion) {
		
		case 'nightly':
			/** @ts-ignore */
			return {
				size: 24583257,
				url: url_nightly,
			};
			

	}
	throw new Error('Unsupported WordPress module: ' + wpVersion);
}
